#/bin/bash

pgrep -f sui-test-validator > /dev/null
if [ $? -eq 0 ]; then
    echo "sui-test-validator already running"
    exit 1;
fi

DEPENDENCIES_DIR=$(pwd)/dependencies
TEST_DIR=$(dirname $0)/../ts/tests
SUI_CONFIG=$TEST_DIR/sui_config

### Remove databases generated by localnet
rm -rf $SUI_CONFIG/*_db

### Start local node
echo "Starting local validator."
sui start \
    --network.config $TEST_DIR/sui_config/network.yaml > /dev/null 2>&1 &

sleep 1

DEVNET_KEY=ACMS4emBUzUD0vcYoiSM2Z8i2qs4MMrKeFRZY3L/pXYK

echo "deploying wormhole contracts to localnet"
bash $DEPENDENCIES_DIR/scripts/deploy.sh devnet \
    -k $DEVNET_KEY

echo "deploying example coins"
worm sui deploy \
    $DEPENDENCIES_DIR/../contracts/example_coins \
    -n devnet -k $DEVNET_KEY -d true

## deploy relayer contracts
echo "deploying hello token"
worm sui deploy \
    $DEPENDENCIES_DIR/../contracts/hello_token \
    -n devnet -k $DEVNET_KEY -d true

## run contract tests here
npx ts-mocha -t 1000000 $TEST_DIR/0[0-9]*.ts

# nuke
pkill sui

# remove databases generated by localnet
rm -rf $SUI_CONFIG/*_db
